config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :server_histories
  resources :servers
  devise_for :users
  root 'servers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/servers/:id/charts/memory', to: 'charts#server_memory', as: 'server_memory_chart'
  get '/servers/:id/charts/cpu', to: 'charts#server_cpu', as: 'server_cpu_chart'
  get '/servers/:id/charts/disk', to: 'charts#server_disk', as: 'server_disk_chart'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/server.rb
class Server < ApplicationRecord
  validates :name, :hostname, :port, presence: true
  has_many :server_histories, dependent: :destroy
  after_initialize :populate_latest_stats
  attr_accessor :latest_stats

  @@no_data_str = "No data available."

  def address 
    if self.hostname.include?('http')
      "#{self.hostname}:#{self.port}"
    else
      "http://#{self.hostname}:#{self.port}"
    end
  end

  def active?
    self.active
  end

  def get_stat(stat)
    return @@no_data_str if @latest_stats.nil?
    eval "@latest_stats.#{stat}"
  end

  def populate_latest_stats
    @latest_stats = self.server_histories.last
  end

  def queue(interval = 0.seconds)
    QueryApiJob.set(wait: interval).perform_later(self.id)
  end

  def self.no_data_str
    @@no_data_str
  end

  def self.queue_all_servers
    servers = Server.all
    return false if servers.size == 0
    servers.each do |s|
      if s.queue 20.seconds
        puts "Queueing query for #{s.name}, (ID: #{s.id})"
      else
        puts "Queueing query for #{s.name}, (ID: #{s.id} failed. See logs."
      end
    end
  end
end

app/models/server_history.rb
class ServerHistory < ApplicationRecord
  belongs_to :server
  after_create :populate_conversions

  def populate_conversions
    unless self.current_ram_usage.nil?
      %w[gb mb kb].each { |size| eval "self.usage_in_#{size} = convert_to_#{size}" }
      self.save
    end
  end
  
  def convert_usage_to_gb
    self.ram_capacity / (1024*1024*1024)
  end

  def convert_usage_to_mb
    self.ram_capacity / (1024*1024)
  end

  def convert_usage_to_kb
    self.ram_capacity / (1024)
  end

  private

  def convert_to_gb
    self.current_ram_usage/(1024*1024*1024)
  end

  def convert_to_mb
    self.current_ram_usage/(1024*1024)
  end

  def convert_to_kb
    self.current_ram_usage/(1024)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  
  def server_memory
    render json: ServerHistory.where(server_id: params[:id]).group_by_minute(:created_at).maximum(:usage_in_mb) 
  end

  def server_cpu
    render json: ServerHistory.where(server_id: params[:id]).group_by_minute(:created_at).maximum(:cpu_load_one)
  end

  def server_disk
    render json: ServerHistory.where(server_id: params[:id]).group_by_minute(:created_at).maximum(:disk_percentage)
  end
end

app/controllers/servers_controller.rb
require 'json'

class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    flash.now[:error] = "Server not accessible." unless @server.active?
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)
    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :hostname, :port)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_boolean(boolean)
    I18n.t((!!boolean).to_s)
  end
end

app/helpers/flash_helper.rb
module FlashHelper
  def bootstrap_alert(key)
    case key
      when 'alert'
        'warning'
      when 'notice'
        'success'
      when 'error'
        'danger'
    end
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/server_histories_helper.rb
module ServerHistoriesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/homepage/index.html.erb
<h1>InaBox Homepage</h1>

<p>Hello, <%= current_user.email %>. There isn't much here yet, but there will be!

<div><%= link_to 'Manage Servers', servers_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InaBox - Agnostic Distributed Computing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid site-wrapper">
      <%= render 'layouts/partials/nav' %>
      <%= render 'layouts/partials/alerts' %>
    </div>

    <div class="container-fluid">
			<div class="content-wrapper">
      	<%= yield %>
			</div>
    </div>

  </body>
</html>

app/views/layouts/partials/_alerts.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= bootstrap_alert key %> fade in alert-dismissable">
  <%= value %>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
</div>
<% end %>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'InaBox', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'New Server', new_server_path %></li>
          <li><%= link_to 'Server List', servers_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/servers/_form.html.erb
<%= form_for(server) do |f| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :hostname %>
    <%= f.text_field :hostname %>
  </div>

  <div class="field">
    <%= f.label :port %>
    <%= f.number_field :port %>
  </div>

  <div class="actions">
    <%= f.submit "Create Server", id: 'create-server' %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<div id="login-panel" class="panel panel-default">
  <div class="panel-heading">
    <p>Editing Server: <%= @server.name %></p>
  </div>
  <div class="panel-body">
    <%= render 'form', server: @server %>

    <%= link_to 'Show', @server %> |
    <%= link_to 'Back', servers_path %>
  </div>
</div>

app/views/servers/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <p>Servers</p>
  </div>

  <div class="panel-body">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Hostname</th>
          <th>Port</th>
          <th>Ram capacity</th>
          <th>Current ram usage</th>
          <th>CPU core count</th>
          <th>Current CPU load</th>
          <th>InaBox Running?</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      <% @servers.each do |server| %>
        <tr>
          <td><%= server.name %></td>
          <td><%= server.hostname %></td>
          <td><%= server.port %></td>
          <td><%= number_to_human_size server.get_stat('ram_capacity') %></td>
          <td><%= number_to_human_size server.get_stat('current_ram_usage') %></td>
          <td><%= server.get_stat('cores_available') %></td>
          <td><%= server.get_stat('cpu_load_one') %></td>
          <td><%= humanize_boolean server.active? %></td>
          <td><%= link_to 'Show', server %></td>
          <td><%= link_to 'Edit', edit_server_path(server) %></td>
          <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<div id="login-panel" class="panel panel-default">
  <div class="panel-heading">
    <p>New Server</p>
  </div>

  <div class="panel-body">
    <%= render 'form', server: @server %>

    <%= link_to 'Back', servers_path %>
  </div>
</div>

app/views/servers/show.html.erb
<div class="col-lg-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <p>Server Information</p>
    </div>
    <div class="panel-body">
      <p>Server Name: <%= @server.name %></p>
      <p>Server Address: <%= @server.hostname %></p>
      <p>Listening Port: <%= @server.port %></p>
    </div>
  </div>
</div>

<div class="col-lg-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <p>CPU Information</p>
    </div>
    <div class="panel-body">
      <div class"row">
        <div class="col-lg-4">
          <p>CPU Count: <%= @server.get_stat('cores_available') %>
          <p>CPU Load Average: <%= @server.get_stat('cpu_load_one') %></p>
        </div>
        <div class="col-lg-8">
        <% if @server.latest_stats.nil? %>
          <%= Server.no_data_str %>
        <% else %>
          <%= line_chart server_cpu_chart_path, max: 100, library: { elements: { point: { radius: 0 } } } %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-10 pull-right">
  <div class="panel panel-default">
    <div class="panel-heading">
      <p>Disk Information</p>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-4">
          <p>Disk Count: <%= @server.get_stat('disk_count') %></p>
          <p>Filesystem Type: <%= @server.get_stat('filesystem') %></p>
          <p>Storage Capacity: <%= number_to_human_size @server.get_stat('storage_capacity') %></p>
          <p>Free Space: <%= number_to_human_size @server.get_stat('free_storage') %></p>
          <% if @server.latest_stats.nil? %>
            <p><%= Server.no_data_str %></p>
          <% else %>
            <p>Percent Free: <%= "#{100 - @server.get_stat('disk_percentage')}%" %></p>
          <% end %>
          <p>Mount Point: <%= @server.get_stat('mount_point') %>
        </div>
        <div class="col-lg-8">
        <% if @server.latest_stats.nil? %>
          <%= Server.no_data_str %>
        <% else %>
          <%= line_chart server_disk_chart_path, max: 100, library: { elements: { point: { radius: 0 } } } %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-lg-10 pull-right">
  <div class="panel panel-default">
    <div class="panel-heading">
      <p>Memory Information</p>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-4">
          <p>Memory Capacity: <%= number_to_human_size @server.get_stat('ram_capacity') %></p>
          <p>Consumed Memory: <%= number_to_human_size @server.get_stat('current_ram_usage') %></p>
          <p>Performance Chart: Memory Snapshot of the last week</p>
        </div>
        <div class="col-lg-8">
        <% if @server.latest_stats.nil? %>
          <p><%= Server.no_data_str %></p>
        <% else %>
          <%= line_chart server_memory_chart_path, max: @server.latest_stats.convert_usage_to_mb, library: { elements: { point: { radius: 0 } } } %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>